In [1]:
# pandas -> analise de dados
# getting started
# quickstart
import pandas as pd

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
})


display(df)
print(df["Age"])
# pd.DataFrame
# pd.DataFrame -> recebe um dicionário como parâmetro e cria a tabela a partir do dicionário

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

0    22
1    35
2    58
Name: Age, dtype: int64

In [2]:
ages = pd.Series([22, 35, 58], name="Age")

print(df["Age"].max())
print(ages.max())

58
58

#### Funções Específicas

In [3]:
# datas no pandas
import pandas as pd

tabela = pd.read_excel("Contratos.xlsx")
tabela['Data Pagamento'] = pd.to_datetime(tabela['Data Pagamento'], format='%d/%m/%Y')
tabela['Data Pagamento 2'] = pd.to_datetime(tabela['Data Pagamento 2'], format='%m-%d-%y')
print(tabela.dtypes)


display(tabela)

Cliente                        str
Data Pagamento      datetime64[us]
Data Pagamento 2    datetime64[us]
dtype: object

    Cliente Data Pagamento Data Pagamento 2
0    Fulano     2022-09-22       2022-09-22
1  Beltrano     2022-04-17       2022-04-17
2   Ciclano     2022-02-21       2022-02-21
3      Lira     2022-12-27       2022-12-27
4     Julia     2022-02-01       2022-02-01
5    Marcus     2022-07-08       2022-07-08
6    Amanda     2022-09-28       2022-09-28
7   Larissa     2022-05-28       2022-05-28
8      Alon     2022-10-06       2022-10-06