In [1]:
# pandas -> analise de dados
# getting started
# quickstart
import pandas as pd

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
})


display(df)
print(df["Age"])
# pd.DataFrame
# pd.DataFrame -> recebe um dicionário como parâmetro e cria a tabela a partir do dicionário

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

0    22
1    35
2    58
Name: Age, dtype: int64

In [2]:
ages = pd.Series([22, 35, 58], name="Age")

print(df["Age"].max())
print(ages.max())

58
58

#### Funções Específicas

In [3]:
# datas no pandas
import pandas as pd

tabela = pd.read_excel("Contratos.xlsx")
tabela['Data Pagamento'] = pd.to_datetime(tabela['Data Pagamento'], format='%d/%m/%Y')
tabela['Data Pagamento 2'] = pd.to_datetime(tabela['Data Pagamento 2'], format='%m-%d-%y')
print(tabela.dtypes)


display(tabela)

Cliente                        str
Data Pagamento      datetime64[us]
Data Pagamento 2    datetime64[us]
dtype: object

    Cliente Data Pagamento Data Pagamento 2
0    Fulano     2022-09-22       2022-09-22
1  Beltrano     2022-04-17       2022-04-17
2   Ciclano     2022-02-21       2022-02-21
3      Lira     2022-12-27       2022-12-27
4     Julia     2022-02-01       2022-02-01
5    Marcus     2022-07-08       2022-07-08
6    Amanda     2022-09-28       2022-09-28
7   Larissa     2022-05-28       2022-05-28
8      Alon     2022-10-06       2022-10-06

In [4]:
# funcao merge do pandas

emails = pd.read_excel("Emails.xlsx")
tabela = tabela.merge(emails, left_on="Cliente", right_on="Nome")
display(tabela)

    Cliente Data Pagamento Data Pagamento 2      Nome               Email
0    Fulano     2022-09-22       2022-09-22    Fulano    fulano@gmail.com
1  Beltrano     2022-04-17       2022-04-17  Beltrano  beltrano@gmail.com
2   Ciclano     2022-02-21       2022-02-21   Ciclano   ciclano@gmail.com
3      Lira     2022-12-27       2022-12-27      Lira      lira@gmail.com
4     Julia     2022-02-01       2022-02-01     Julia     julia@gmail.com
5    Marcus     2022-07-08       2022-07-08    Marcus    marcus@gmail.com
6    Amanda     2022-09-28       2022-09-28    Amanda    amanda@gmail.com
7   Larissa     2022-05-28       2022-05-28   Larissa   larissa@gmail.com
8      Alon     2022-10-06       2022-10-06      Alon      alon@gmail.com

In [5]:
# funcao datetime

from datetime import datetime

hoje = datetime(2022, 12, 15)
print(hoje)

2022-12-15 00:00:00

#### APIs

In [7]:

# exemplo sandbox https://dadosabertos.bcb.gov.br/dataset/dinheiro-em-circulao

# exemplo documentação: https://www.alphavantage.co/

import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=IBM&apikey=dfsdhfsiufhsfuishfis'
r = requests.get(url)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Weekly Adjusted Prices and Volumes', '2. Symbol': 'IBM', '3. Last Refreshed': '2026-04-20', '4. Time Zone': 'US/Eastern'}, 'Weekly Adjusted Time Series': {'2026-04-20': {'1. open': '255.0000', '2. high': '258.5000', '3. low': '252.5600', '4. close': '253.7100', '5. adjusted close': '253.7100', '6. volume': '5157714', '7. dividend amount': '0.0000'}, '2026-04-17': {'1. open': '233.6300', '2. high': '255.6500', '3. low': '231.7000', '4. close': '253.4700', '5. adjusted close': '253.4700', '6. volume': '23495380', '7. dividend amount': '0.0000'}, '2026-04-10': {'1. open': '248.1400', '2. high': '250.0000', '3. low': '230.5100', '4. close': '230.7600', '5. adjusted close': '230.7600', '6. volume': '21451523', '7. dividend amount': '0.0000'}, '2026-04-02': {'1. open': '237.8000', '2. high': '248.2103', '3. low': '236.1310', '4. close': '248.1600', '5. adjusted close': '248.1600', '6. volume': '16212406', '7. dividend amount': '0.0000'}, '2026-03-27': {'1. open': '246.5000', '2. high': '251.3500', '3. low': '233.7500', '4. close': '236.3400', '5. adjusted close': '236.3400', '6. volume': '21791992', '7. dividend amount': '0.0000'}, '2026-03-20': {'1. open': '247.8700', '2. high': '258.2800', '3. low': '241.7700', '4. close': '241.7700', '5. adjusted close': '241.7700', '6. volume': '32254965', '7. dividend amount': '0.0000'}, '2026-03-13': {'1. open': '255.3800', '2. high': '258.0800', '3. low': '244.7100', '4. close': '246.2800', '5. adjusted close': '246.2800', '6. volume': '24962921', '7. dividend amount': '0.0000'}, '2026-03-06': {'1. open': '235.7000', '2. high': '260.3800', '3. low': '233.7800', '4. close': '258.8500', '5. adjusted close': '258.8500', '6. volume': '35400015', '7. dividend amount': '0.0000'}, '2026-02-27': {'1. open': '254.3700', '2. high': '255.1900', '3. low': '220.7200', '4. close': '240.2100', '5. adjusted close': '240.2100', '6. volume': '55457688', '7. dividend amount': '0.0000'}, '2026-02-20': {'1. open': '259.2000', '2. high': '261.1100', '3. low': '253.5110', '4. close': '257.1600', '5. adjusted close': '257.1600', '6. volume': '18536212', '7. dividend amount': '0.0000'}, '2026-02-13': {'1. open': '295.9100', '2. high': '297.7200', '3. low': '256.6400', '4. close': '262.3800', '5. adjusted close': '262.3800', '6. volume': '35501402', '7. dividend amount': '1.6800'}, '2026-02-06': {'1. open': '307.5100', '2. high': '316.6400', '3. low': '278.9600', '4. close': '298.9300', '5. adjusted close': '297.2186', '6. volume': '33862352', '7. dividend amount': '0.0000'}, '2026-01-30': {'1. open': '293.1600', '2. high': '319.9000', '3. low': '291.2601', '4. close': '306.7000', '5. adjusted close': '304.9441', '6. volume': '28527557', '7. dividend amount': '0.0000'}, '2026-01-23': {'1. open': '301.3500', '2. high': '301.6000', '3. low': '289.7900', '4. close': '292.4400', '5. adjusted close': '290.7657', '6. volume': '19365305', '7. dividend amount': '0.0000'}, '2026-01-16': {'1. open': '302.6200', '2. high': '312.8100', '3. low': '297.0400', '4. close': '305.6700', '5. adjusted close': '303.9200', '6. volume': '23314117', '7. dividend amount': '0.0000'}, '2026-01-09': {'1. open': '295.7700', '2. high': '307.0000', '3. low': '294.2500', '4. close': '304.2200', '5. adjusted close': '302.4783', '6. volume': '17232650', '7. dividend amount': '0.0000'}, '2026-01-02': {'1. open': '304.6500', '2. high': '310.0000', '3. low': '289.0000', '4. close': '291.5000', '5. adjusted close': '289.8311', '6. volume': '14641299', '7. dividend amount': '0.0000'}, '2025-12-26': {'1. open': '301.0300', '2. high': '305.7500', '3. low': '298.3200', '4. close': '305.0900', '5. adjusted close': '303.3433', '6. volume': '9560511', '7. dividend amount': '0.0000'}, '2025-12-19': {'1. open': '308.9850', '2. high': '311.3629', '3. low': '295.7000', '4. close': '300.9800', '5. adjusted close': '299.2568', '6. volume': '26507574', '7. dividend amount': '0.0000'}, '2025-12-12': {'1. open': '309.6200', '2. high': '315.3454', '3. low': '303.3300', '4. close': '309.2400', '5. adjusted close': '307.4695', '6. volume': '15650716', '7. dividend amount': '0.0000'}, '2025-12-05': {'1. open': '306.5050', '2. high': '311.8300', '3. low': '298.9050', '4. close': '307.9400', '5. adjusted close': '306.1770', '6. volume': '16688175', '7. dividend amount': '0.0000'}, '2025-11-28': {'1. open': '299.1800', '2. high': '309.1800', '3. low': '297.0600', '4. close': '308.5800', '5. adjusted close': '306.8133', '6. volume': '12761439', '7. dividend amount': '0.0000'}, '2025-11-21': {'1. open': '305.5900', '2. high': '306.0000', '3. low': '288.0700', '4. close': '297.4400', '5. adjusted close': '295.7371', '6. volume': '23675512', '7. dividend amount': '0.0000'}, '2025-11-14': {'1. open': '306.8200', '2. high': '324.9000', '3. low': '297.5900', '4. close': '305.6900', '5. adjusted close': '303.9399', '6. volume': '22302392', '7. dividend amount': '1.6800'}, '2025-11-07': {'1. open': '308.0000', '2. high': '315.4400', '3. low': '296.0000', '4. close': '306.3800', '5. adjusted close': '302.9793', '6. volume': '27157777', '7. dividend amount': '0.0000'}, '2025-10-31': {'1. open': '307.8000', '2. high': '319.3500', '3. low': '301.6300', '4. close': '307.4100', '5. adjusted close': '303.9979', '6. volume': '32440643', '7. dividend amount': '0.0000'}, '2025-10-24': {'1. open': '281.2500', '2. high': '310.7500', '3. low': '263.5623', '4. close': '307.4600', '5. adjusted close': '304.0474', '6. volume': '51704434', '7. dividend amount': '0.0000'}, '2025-10-17': {'1. open': '279.7900', '2. high': '285.4500', '3. low': '272.5469', '4. close': '281.2800', '5. adjusted close': '278.1579', '6. volume': '19005226', '7. dividend amount': '0.0000'}, '2025-10-10': {'1. open': '288.6100', '2. high': '301.0425', '3. low': '277.5000', '4. close': '277.8200', '5. adjusted close': '274.7363', '6. volume': '24789984', '7. dividend amount': '0.0000'}, '2025-10-03': {'1. open': '286.0000', '2. high': '293.3200', '3. low': '279.6600', '4. close': '288.3700', '5. adjusted close': '285.1692', '6. volume': '24519701', '7. dividend amount': '0.0000'}, '2025-09-26': {'1. open': '266.6200', '2. high': '288.8500', '3. low': '266.0000', '4. close': '284.3100', '5. adjusted close': '281.1543', '6. volume': '34154715', '7. dividend amount': '0.0000'}, '2025-09-19': {'1. open': '254.0200', '2. high': '267.8700', '3. low': '254.0000', '4. close': '266.4000', '5. adjusted close': '263.4431', '6. volume': '25569601', '7. dividend amount': '0.0000'}, '2025-09-12': {'1. open': '248.6300', '2. high': '260.6600', '3. low': '247.0200', '4. close': '253.4400', '5. adjusted close': '250.6269', '6. volume': '24066143', '7. dividend amount': '0.0000'}, '2025-09-05': {'1. open': '240.9000', '2. high': '249.2800', '3. low': '238.2500', '4. close': '248.5300', '5. adjusted close': '245.7714', '6. volume': '14538355', '7. dividend amount': '0.0000'}, '2025-08-29': {'1. open': '242.5650', '2. high': '245.9600', '3. low': '239.4300', '4. close': '243.4900', '5. adjusted close': '240.7874', '6. volume': '18386656', '7. dividend amount': '0.0000'}, '2025-08-22': {'1. open': '239.5700', '2. high': '243.6800', '3. low': '238.6500', '4. close': '242.0900', '5. adjusted close': '239.4029', '6. volume': '16264747', '7. dividend amount': '0.0000'}, '2025-08-15': {'1. open': '242.2400', '2. high': '243.1500', '3. low': '233.3600', '4. close': '239.7200', '5. adjusted close': '237.0592', '6. volume': '32747166', '7. dividend amount': '0.0000'}, '2025-08-08': {'1. open': '251.0500', '2. high': '255.0000', '3. low': '241.6500', '4. close': '242.2700', '5. adjusted close': '239.5809', '6. volume': '27875384', '7. dividend amount': '1.6800'}, '2025-08-01': {'1. open': '260.3000', '2. high': '265.7999', '3. low': '245.6100', '4. close': '250.0500', '5. adjusted close': '245.5717', '6. volume': '29960567', '7. dividend amount': '0.0000'}, '2025-07-25': {'1. open': '286.2900', '2. high': '288.0800', '3. low': '252.7500', '4. close': '259.7200', '5. adjusted close': '255.0685', '6. volume': '46388289', '7. dividend amount': '0.0000'}, '2025-07-18': {'1. open': '282.8300', '2. high': '287.1600', '3. low': '279.8700', '4. close': '285.8700', '5. adjusted close': '280.7502', '6. volume': '16341671', '7. dividend amount': '0.0000'}, '2025-07-11': {'1. open': '292.5000', '2. high': '295.6100', '3. low': '282.2100', '4. close': '283.5900', '5. adjusted close': '278.5110', '6. volume': '17664449', '7. dividend amount': '0.0000'}, '2025-07-03': {'1. open': '290.9300', '2. high': '295.1081', '3. low': '286.9000', '4. close': '291.9700', '5. adjusted close': '286.7409', '6. volume': '11878987', '7. dividend amount': '0.0000'}, '2025-06-27': {'1. open': '281.6500', '2. high': '296.1600', '3. low': '280.2100', '4. close': '289.7000', '5. adjusted close': '284.5116', '6. volume': '19051199', '7. dividend amount': '0.0000'}, '2025-06-20': {'1. open': '279.3050', '2. high': '286.9100', '3. low': '277.2000', '4. close': '280.9700', '5. adjusted close': '275.9379', '6. volume': '17965949', '7. dividend amount': '0.0000'}, '2025-06-13': {'1. open': '268.1000', '2. high': '283.0600', '3. low': '266.7100', '4. close': '277.2200', '5. adjusted close': '272.2551', '6. volume': '20812836', '7. dividend amount': '0.0000'}, '2025-06-06': {'1. open': '257.8500', '2. high': '270.1700', '3. low': '257.2200', '4. close': '268.8700', '5. adjusted close': '264.0546', '6. volume': '13070565', '7. dividend amount': '0.0000'}, '2025-05-30': {'1. open': '261.0000', '2. high': '265.0000', '3. low': '256.7700', '4. close': '259.0600', '5. adjusted close': '254.4203', '6. volume': '17566804', '7. dividend amount': '0.0000'}, '2025-05-23': {'1. open': '265.4500', '2. high': '269.2800', '3. low': '255.7900', '4. close': '258.6300', '5. adjusted close': '253.9980', '6. volume': '15204641', '7. dividend amount': '0.0000'}, '2025-05-16': {'1. open': '252.5000', '2. high': '267.9800', '3. low': '244.6500', '4. close': '266.7600', '5. adjusted close': '261.9824', '6. volume': '20440246', '7. dividend amount': '0.0000'}, '2025-05-09': {'1. open': '243.7400', '2. high': '256.5200', '3. low': '243.6400', '4. close': '249.2000', '5. adjusted close': '244.7369', '6. volume': '16977083', '7. dividend amount': '1.6800'}, '2025-05-02': {'1. open': '232.8600', '2. high': '245.6900', '3. low': '232.0700', '4. close': '245.5500', '5. adjusted close': '239.5374', '6. volume': '20198202', '7. dividend amount': '0.0000'}, '2025-04-25': {'1. open': '238.0650', '2. high': '249.3400', '3. low': '224.4401', '4. close': '232.4100', '5. adjusted close': '226.7192', '6. volume': '39218052', '7. dividend amount': '0.0000'}, '2025-04-17': {'1. open': '239.7700', '2. high': '243.2999', '3. low': '235.8900', '4. close': '238.8100', '5. adjusted close': '232.9625', '6. volume': '16190928', '7. dividend amount': '0.0000'}, '2025-04-11': {'1. open': '219.2400', '2. high': '237.5800', '3. low': '214.5000', '4. close': '235.4800', '5. adjusted close': '229.7140', '6. volume': '31932696', '7. dividend amount': '0.0000'}, '2025-04-04': {'1. open': '242.7400', '2. high': '252.7900', '3. low': '226.8800', '4. close': '227.4800', '5. adjusted close': '221.9099', '6. volume': '28005665', '7. dividend amount': '0.0000'}, '2025-03-28': {'1. open': '247.3100', '2. high': '254.3200', '3. low': '242.0700', '4. close': '244.0000', '5. adjusted close': '238.0254', '6. volume': '18354282', '7. dividend amount': '0.0000'}, '2025-03-21': {'1. open': '249.2500', '2. high': '254.6300', '3. low': '237.2240', '4. close': '243.8700', '5. adjusted close': '237.8986', '6. volume': '27866866', '7. dividend amount': '0.0000'}, '2025-03-14': {'1. open': '261.5600', '2. high': '266.4500', '3. low': '241.6800', '4. close': '248.3500', '5. adjusted close': '242.2689', '6. volume': '25513710', '7. dividend amount': '0.0000'}, '2025-03-07': {'1. open': '254.7350', '2. high': '261.9600', '3. low': '245.1823', '4. close': '261.5400', '5. adjusted close': '255.1359', '6. volume': '22284160', '7. dividend amount': '0.0000'}, '2025-02-28': {'1. open': '261.5000', '2. high': '263.8450', '3. low': '246.5400', '4. close': '252.4400', '5. adjusted close': '246.2587', '6. volume': '25541761', '7. dividend amount': '0.0000'}, '2025-02-21': {'1. open': '261.9300', '2. high': '265.0900', '3. low': '259.8300', '4. close': '261.4800', '5. adjusted close': '255.0774', '6. volume': '18534169', '7. dividend amount': '0.0000'}, '2025-02-14': {'1. open': '250.8600', '2. high': '261.9400', '3. low': '246.8700', '4. close': '261.2800', '5. adjusted close': '254.8822', '6. volume': '19898073', '7. dividend amount': '1.6700'}, '2025-02-07': {'1. open': '252.4000', '2. high': '265.7200', '3. low': '251.8400', '4. close': '252.3400', '5. adjusted close': '244.5230', '6. volume': '30149848', '7. dividend amount': '0.0000'}, '2025-01-31': {'1. open': '222.1900', '2. high': '261.8000', '3. low': '219.8400', '4. close': '255.7000', '5. adjusted close': '247.7789', '6. volume': '39048997', '7. dividend amount': '0.0000'}, '2025-01-24': {'1. open': '224.9900', '2. high': '227.4500', '3. low': '220.3500', '4. close': '224.8000', '5. adjusted close': '217.8361', '6. volume': '15594637', '7. dividend amount': '0.0000'}, '2025-01-17': {'1. open': '217.8900', '2. high': '225.9550', '3. low': '214.6100', '4. close': '224.7900', '5. adjusted close': '217.8264', '6. volume': '18990367', '7. dividend amount': '0.0000'}, '2025-01-10': {'1. open': '223.0000', '2. high': '226.7110', '3. low': '216.8000', '4. close': '219.7500', '5. adjusted close': '212.9425', '6. volume': '12337094', '7. dividend amount': '0.0000'}, '2025-01-03': {'1. open': '220.5400', '2. high': '223.6600', '3. low': '217.6000', '4. close': '222.6500', '5. adjusted close': '215.7527', '6. volume': '10819153', '7. dividend amount': '0.0000'}, '2024-12-27': {'1. open': '222.8100', '2. high': '225.4000', '3. low': '221.0800', '4. close': '222.7800', '5. adjusted close': '215.8787', '6. volume': '9272351', '7. dividend amount': '0.0000'}, '2024-12-20': {'1. open': '230.7300', '2. high': '231.0300', '3. low': '220.0300', '4. close': '223.3600', '5. adjusted close': '216.4407', '6. volume': '28267440', '7. dividend amount': '0.0000'}, '2024-12-13': {'1. open': '238.0000', '2. high': '239.3500', '3. low': '227.8000', '4. close': '230.8200', '5. adjusted close': '223.6696', '6. volume': '20886084', '7. dividend amount': '0.0000'}, '2024-12-06': {'1. open': '227.5000', '2. high': '238.3800', '3. low': '225.5100', '4. close': '238.0400', '5. adjusted close': '230.6659', '6. volume': '18743737', '7. dividend amount': '0.0000'}, '2024-11-29': {'1. open': '223.3500', '2. high': '230.3600', '3. low': '222.6500', '4. close': '227.4100', '5. adjusted close': '220.3652', '6. volume': '17274177', '7. dividend amount': '0.0000'}, '2024-11-22': {'1. open': '207.0000', '2. high': '227.2000', '3. low': '205.3701', '4. close': '222.9700', '5. adjusted close': '216.0628', '6. volume': '21386866', '7. dividend amount': '0.0000'}, '2024-11-15': {'1. open': '214.4000', '2. high': '215.4100', '3. low': '204.0700', '4. close': '204.9900', '5. adjusted close': '198.6398', '6. volume': '19438346', '7. dividend amount': '1.6700'}, '2024-11-08': {'1. open': '207.6500', '2. high': '216.7000', '3. low': '205.5700', '4. close': '213.7200', '5. adjusted close': '205.4720', '6. volume': '15846890', '7. dividend amount': '0.0000'}, '2024-11-01': {'1. open': '215.5000', '2. high': '216.2500', '3. low': '203.5100', '4. close': '208.2500', '5. adjusted close': '200.2131', '6. volume': '26467891', '7. dividend amount': '0.0000'}, '2024-10-25': {'1. open': '231.2100', '2. high': '233.3400', '3. low': '214.3850', '4. close': '214.6700', '5. adjusted close': '206.3853', '6. volume': '31380820', '7. dividend amount': '0.0000'}, '2024-10-18': {'1. open': '233.5700', '2. high': '237.3700', '3. low': '230.1700', '4. close': '232.2000', '5. adjusted close': '223.2388', '6. volume': '18477394', '7. dividend amount': '0.0000'}, '2024-10-11': {'1. open': '225.3800', '2. high': '235.8300', '3. low': '225.0200', '4. close': '233.2600', '5. adjusted close': '224.2579', '6. volume': '18398213', '7. dividend amount': '0.0000'}, '2024-10-04': {'1. open': '220.6500', '2. high': '226.0800', '3. low': '215.7980', '4. close': '226.0000', '5. adjusted close': '217.2781', '6. volume': '17778630', '7. dividend amount': '0.0000'}, '2024-09-27': {'1. open': '218.0000', '2. high': '224.1500', '3. low': '217.2700', '4. close': '220.8400', '5. adjusted close': '212.3172', '6. volume': '16300165', '7. dividend amount': '0.0000'}, '2024-09-20': {'1. open': '215.8800', '2. high': '218.8400', '3. low': '210.3700', '4. close': '217.7000', '5. adjusted close': '209.2984', '6. volume': '28532770', '7. dividend amount': '0.0000'}, '2024-09-13': {'1. open': '201.9400', '2. high': '216.0900', '3. low': '201.4300', '4. close': '214.7900', '5. adjusted close': '206.5007', '6. volume': '21518747', '7. dividend amount': '0.0000'}, '2024-09-06': {'1. open': '201.9100', '2. high': '205.9500', '3. low': '199.3350', '4. close': '200.7400', '5. adjusted close': '192.9929', '6. volume': '13519865', '7. dividend amount': '0.0000'}, '2024-08-30': {'1. open': '196.0000', '2. high': '202.1700', '3. low': '195.9000', '4. close': '202.1300', '5. adjusted close': '194.3293', '6. volume': '15570283', '7. dividend amount': '0.0000'}, '2024-08-23': {'1. open': '193.8400', '2. high': '197.9200', '3. low': '193.7150', '4. close': '196.1000', '5. adjusted close': '188.5320', '6. volume': '11022549', '7. dividend amount': '0.0000'}, '2024-08-16': {'1. open': '191.2500', '2. high': '194.3500', '3. low': '189.0001', '4. close': '193.7800', '5. adjusted close': '186.3015', '6. volume': '11330854', '7. dividend amount': '0.0000'}, '2024-08-09': {'1. open': '184.5500', '2. high': '192.8800', '3. low': '181.8100', '4. close': '191.4500', '5. adjusted close': '184.0615', '6. volume': '18895865', '7. dividend amount': '1.6700'}, '2024-08-02': {'1. open': '193.1800', '2. high': '194.5499', '3. low': '185.7000', '4. close': '189.1200', '5. adjusted close': '180.2491', '6. volume': '20594367', '7. dividend amount': '0.0000'}, '2024-07-26': {'1. open': '183.4000', '2. high': '196.2600', '3. low': '182.8600', '4. close': '191.7500', '5. adjusted close': '182.7557', '6. volume': '25458498', '7. dividend amount': '0.0000'}, '2024-07-19': {'1. open': '183.3800', '2. high': '189.4700', '3. low': '181.9500', '4. close': '183.2500', '5. adjusted close': '174.6544', '6. volume': '17829469', '7. dividend amount': '0.0000'}, '2024-07-12': {'1. open': '176.4100', '2. high': '184.1600', '3. low': '174.4500', '4. close': '182.8300', '5. adjusted close': '174.2541', '6. volume': '16071235', '7. dividend amount': '0.0000'}, '2024-07-05': {'1. open': '173.4500', '2. high': '177.9800', '3. low': '173.3800', '4. close': '176.0200', '5. adjusted close': '167.7636', '6. volume': '9939255', '7. dividend amount': '0.0000'}, '2024-06-28': {'1. open': '175.0000', '2. high': '178.4599', '3. low': '170.4100', '4. close': '172.9500', '5. adjusted close': '164.8376', '6. volume': '18850478', '7. dividend amount': '0.0000'}, '2024-06-21': {'1. open': '168.7600', '2. high': '174.9600', '3. low': '167.5000', '4. close': '172.4600', '5. adjusted close': '164.3705', '6. volume': '21531360', '7. dividend amount': '0.0000'}, '2024-06-14': {'1. open': '169.5500', '2. high': '172.4700', '3. low': '166.8100', '4. close': '169.2100', '5. adjusted close': '161.2730', '6. volume': '16222067', '7. dividend amount': '0.0000'}, '2024-06-07': {'1. open': '166.5400', '2. high': '171.3050', '3. low': '163.5300', '4. close': '170.0100', '5. adjusted close': '162.0355', '6. volume': '14102396', '7. dividend amount': '0.0000'}, '2024-05-31': {'1. open': '170.4400', '2. high': '171.0850', '3. low': '163.8400', '4. close': '166.8500', '5. adjusted close': '159.0237', '6. volume': '15594186', '7. dividend amount': '0.0000'}, '2024-05-24': {